import path from 'node:path';

import type {
  SeliConfigV2,
  ProjectSkillConfigV2,
  RegistriesSnapshotV2,
  TeamProviderConfigV2
} from './contracts.js';
import { loadProfile } from '../infrastructure/catalog.js';
import { deepClone } from '../infrastructure/json.js';
import { uniqueStrings } from '../infrastructure/fs.js';

export const CONFIG_RELATIVE_PATH_V2 = '.selirc';
export const LOCK_RELATIVE_PATH_V2 = '.seli.lock';

export const REQUIRED_PROJECT_SKILLS: ProjectSkillConfigV2[] = [
  {
    id: 'repo-governance',
    description: 'Generic repository governance and topology guardrails.',
    managed: true
  },
  {
    id: 'change-closeout',
    description: 'Generic repo-local closeout checklist and reporting template.',
    managed: true
  },
  {
    id: 'stack-bootstrap-guide',
    description: 'Guide stack selection and bootstrap execution for new or near-empty repositories.',
    managed: true,
    whenToUse: [
      'Use by default when onboarding a new or near-empty repository and the user has not locked a technology stack yet.',
      'Use when the user asks for a baseline scaffold and wants the agent to help choose between viable stacks.',
      'Use for existing repositories only when the user explicitly asks to revisit stack direction.'
    ],
    workflow: [
      'First classify repository state: new/near-empty versus existing codebase with established stack.',
      'If the user has no stack preference, propose 2-3 candidate stacks with tradeoffs and require user confirmation before implementation.',
      'If the user already selected a stack, prioritize that choice and only suggest alternatives when hard constraints conflict.',
      'After stack confirmation, produce and execute a bootstrap checklist covering target structure, initialization commands, and minimum run verification.',
      'Record the final stack decision in intake decisions using id pattern stack-*, and capture constraints in intake notes (deployment, team familiarity, performance, budget).'
    ],
    guardrails: [
      'Final stack choice stays with the user; do not lock a stack without explicit user confirmation.',
      'Do not force stack-discovery dialogs for established repositories unless the user asks for stack changes.',
      'Treat this guidance as decision support only; scaffold code should be generated by follow-up agent execution, not by hard-coded seli templates.'
    ]
  },
  {
    id: 'git-management-guide',
    description: 'Guide repository Git initialization and delivery workflow after project bootstrap.',
    managed: true,
    whenToUse: [
      'Use immediately after a new project scaffold is created to establish a consistent Git workflow.',
      'Use when a repository exists but Git conventions (branching, commit hygiene, remote flow) are not explicit.',
      'Use for existing mature repositories only when the user asks to adjust Git process.'
    ],
    workflow: [
      'After scaffold generation, verify whether Git is initialized; if not, initialize repository state and confirm default branch policy with the user (fallback main).',
      'Ensure baseline ignore and housekeeping files are present before the first meaningful commit.',
      'Create the initial baseline commit with a clear message describing scaffold and repository setup.',
      'If the user provides remote details, guide remote binding and first push flow; otherwise record that remote setup is pending.',
      'For follow-up work, guide branch-per-change and review-ready commit practices aligned with the repository contract.',
      'Record Git process decisions in intake decisions using id pattern git-*, and capture constraints in intake notes (branch model, protected branch rules, CI requirements).'
    ],
    guardrails: [
      'Do not rewrite history or force-push without explicit user approval.',
      'Do not assume remote hosting provider or branch protection defaults; confirm or record assumptions.',
      'Keep this as behavioral guidance only; seli should not hard-code provider-specific Git automation.'
    ]
  },
  {
    id: 'team-skill-evolution',
    description: 'Expand and refresh team skill coverage as the project matures.',
    managed: true,
    whenToUse: [
      'Use when the project enters a new phase, adds new technical scope, or needs additional team skills beyond the initial bootstrap.'
    ],
    workflow: [
      'Read AGENTS.md, .selirc, and .seli.lock before choosing new team skills.',
      'Review the current repository structure, uploaded docs, and configured team skill packages to identify capability gaps.',
      'Prepare intake changes for the new team skill selection, then run plan, update, and doctor.'
    ],
    guardrails: [
      'Add team skills incrementally based on current project evidence instead of enabling every available skill.',
      'Prefer project-local skills when repository-specific guidance should override the team layer.'
    ]
  },
  {
    id: 'team-skill-sync',
    description: 'Keep mounted team skills aligned with external package updates and replacements.',
    managed: true,
    whenToUse: [
      'Use when team skill packages change on disk, new packages are introduced, or existing package contents have been updated.'
    ],
    workflow: [
      'Compare the current package scan against .seli.lock to find added, removed, or changed team skills.',
      'Adjust the selected team skills when a package change affects the project capability set.',
      'Run plan, update, and doctor to refresh symlinks, lock fingerprints, and validation state.'
    ],
    guardrails: [
      'Treat lock drift as a signal to rescan package contents before changing team skill selections.',
      'Do not edit mounted team skills inside the project; update the source package or rerun seli.'
    ]
  }
];

function normalizeProvider(provider: TeamProviderConfigV2): TeamProviderConfigV2 {
  const packages = (provider.packages ?? []).map((item, index) => ({
    id: item.id,
    label: item.label || path.basename(item.rootPath) || provider.id,
    materializationMode: item.materializationMode || provider.materializationMode || 'symlink',
    priority: item.priority ?? index,
    rootPath: path.resolve(item.rootPath)
  }));
  return {
    id: provider.id,
    materializationMode: provider.materializationMode || 'symlink',
    sourceRoot: provider.sourceRoot ? path.resolve(provider.sourceRoot) : packages[0]?.rootPath,
    packages,
    skills: uniqueStrings(provider.skills ?? [])
  };
}

function ensureRequiredProjectSkills(skills: ProjectSkillConfigV2[]): ProjectSkillConfigV2[] {
  const existing = new Map(skills.map(skill => [skill.id, skill]));
  const required = REQUIRED_PROJECT_SKILLS.map(item => ({
    ...item,
    ...existing.get(item.id),
    managed: true,
    guardrails: uniqueStrings([...(item.guardrails ?? []), ...(existing.get(item.id)?.guardrails ?? [])]),
    relatedTeamSkills: uniqueStrings(existing.get(item.id)?.relatedTeamSkills ?? item.relatedTeamSkills ?? []),
    sourceDocumentLabels: uniqueStrings(existing.get(item.id)?.sourceDocumentLabels ?? item.sourceDocumentLabels ?? []),
    sourcePaths: uniqueStrings(existing.get(item.id)?.sourcePaths ?? item.sourcePaths ?? []).map(p => path.resolve(p)),
    whenToUse: uniqueStrings([...(item.whenToUse ?? []), ...(existing.get(item.id)?.whenToUse ?? [])]),
    workflow: uniqueStrings([...(item.workflow ?? []), ...(existing.get(item.id)?.workflow ?? [])])
  }));

  const others = skills.filter(skill => !required.some(item => item.id === skill.id));
  return [...required, ...others];
}

export function buildRegistriesSnapshotDefault(): RegistriesSnapshotV2 {
  return {
    commands: [],
    providers: [],
    renderers: [],
    policies: [],
    doctorChecks: []
  };
}

export function buildConfigFromProfileV2(profileId = 'default'): SeliConfigV2 {
  const profile = loadProfile(profileId);
  const source = deepClone(profile.config);

  return normalizeConfigV2({
    version: 2,
    profile: source.profile,
    platforms: {
      codex: { enabled: source.platforms.codex.enabled },
      claude: { enabled: source.platforms.claude.enabled }
    },
    layers: {
      system: {
        baselineVersion: source.layers.system.baselineVersion,
        modules: [...source.layers.system.modules]
      },
      team: {
        providers: source.layers.team.providers.map(provider => ({
          id: provider.id,
          materializationMode: provider.materializationMode,
          sourceRoot: undefined,
          packages: [],
          skills: [...provider.skills]
        }))
      },
      project: {
        skills: source.layers.project.skills.map(skill => ({ ...skill })),
        compatPlugin: {
          enabled: false,
          pluginId: 'disabled'
        },
        extraAgents: [...source.layers.project.extraAgents]
      }
    },
    policies: {
      overwriteManagedFiles: source.policies.overwriteManagedFiles,
      drift: source.policies.drift,
      symlink: source.policies.symlink,
      compat: source.policies.compat
    },
    plugins: {
      enabled: ['provider:ecc', 'renderer:base', 'renderer:codex', 'renderer:claude', 'policy:team-skill-selection', 'policy:drift-check', 'doctor:managed-state', 'doctor:provider-state', 'doctor:claude-entrypoint', 'doctor:duplicate-skills']
    },
    registriesSnapshot: buildRegistriesSnapshotDefault(),
    commandDefaults: {
      output: 'explain',
      force: false
    }
  });
}

export function normalizeConfigV2(input: SeliConfigV2): SeliConfigV2 {
  const config = deepClone(input);

  config.version = 2;
  config.profile = config.profile || 'default';
  config.platforms = config.platforms || { codex: { enabled: true }, claude: { enabled: true } };
  config.platforms.codex = config.platforms.codex || { enabled: true };
  config.platforms.claude = config.platforms.claude || { enabled: true };

  config.layers = config.layers || {
    system: { baselineVersion: '2.0.0', modules: ['codex', 'claude'] },
    team: { providers: [] },
    project: {
      skills: [],
      compatPlugin: { enabled: false, pluginId: 'disabled' },
      extraAgents: ['explorer', 'reviewer']
    }
  };
  config.layers.system = config.layers.system || { baselineVersion: '2.0.0', modules: ['codex', 'claude'] };
  config.layers.system.modules = uniqueStrings(config.layers.system.modules || ['codex', 'claude']);

  config.layers.team = config.layers.team || { providers: [] };
  config.layers.team.providers = (config.layers.team.providers || []).map(provider => normalizeProvider(provider));

  config.layers.project = config.layers.project || {
    skills: [],
    compatPlugin: { enabled: false, pluginId: 'disabled' },
    extraAgents: ['explorer', 'reviewer']
  };
  config.layers.project.skills = ensureRequiredProjectSkills(
    (config.layers.project.skills || []).map(skill => ({
      ...skill,
      managed: skill.managed !== false,
      guardrails: uniqueStrings(skill.guardrails || []),
      relatedTeamSkills: uniqueStrings(skill.relatedTeamSkills || []),
      sourceDocumentLabels: uniqueStrings(skill.sourceDocumentLabels || []),
      sourcePaths: uniqueStrings(skill.sourcePaths || []).map(item => path.resolve(item)),
      whenToUse: uniqueStrings(skill.whenToUse || []),
      workflow: uniqueStrings(skill.workflow || [])
    }))
  );

  config.layers.project.compatPlugin = {
    enabled: false,
    pluginId: 'disabled'
  };
  config.layers.project.extraAgents = uniqueStrings(config.layers.project.extraAgents || ['explorer', 'reviewer']);

  config.policies = config.policies || {
    overwriteManagedFiles: false,
    drift: 'error',
    symlink: 'relative',
    compat: 'minimal'
  };
  config.policies.overwriteManagedFiles = Boolean(config.policies.overwriteManagedFiles);
  config.policies.drift = config.policies.drift || 'error';
  config.policies.symlink = config.policies.symlink || 'relative';
  config.policies.compat = config.policies.compat || 'minimal';

  config.plugins = config.plugins || { enabled: [] };
  config.plugins.enabled = uniqueStrings(config.plugins.enabled || []);

  config.registriesSnapshot = config.registriesSnapshot || buildRegistriesSnapshotDefault();
  config.commandDefaults = config.commandDefaults || { output: 'explain', force: false };

  return config;
}
