# {{pluginId}}

Compatibility-only plugin generated by `seli`.

- Primary configuration still lives in `.selirc`, `.seli.lock`, `.codex/`, `.claude/`, and `.agents/`.
- This plugin exists only for repo-local compatibility flows.
