# {{pluginId}}

Compatibility-only plugin generated by `ai-tool-init`.

- Primary configuration still lives in `.ai-tool-init/`, `.codex/`, `.claude/`, and `.agents/`.
- This plugin exists only for repo-local compatibility flows.
