{
  "name": "{{pluginId}}",
  "version": "0.1.0",
  "description": "Repo-local compatibility plugin generated by seli.",
  "skills": "./skills/",
  "interface": {
    "displayName": "Seli Compat",
    "shortDescription": "Repo-local compatibility plugin for generated project skills.",
    "longDescription": "This compatibility plugin exposes repo-local project skills for compatibility workflows. It is not the primary configuration entrypoint.",
    "developerName": "seli",
    "category": "Engineering",
    "capabilities": [
      "Read",
      "Write"
    ]
  }
}
