---
name: {{skillId}}
description: {{skillDescription}}
---

# {{skillId}}

This is a repo-local project skill generated by `ai-tool-init`.

Use this skill when repository-specific guidance must override the team layer.

## When To Use

{{whenToUse}}

## Workflow

{{workflow}}

## Source Material

{{sourceMaterial}}

## Related Team Skills

{{relatedTeamSkills}}

## Guardrails

- Keep the skill concise and repository-specific.
- Treat this project skill as higher priority than `.agents/skills/{{skillId}}` when both exist.
- Treat `.claude/skills/{{skillId}}` as the same repo-local skill content exposed through the Claude entrypoint.
- Keep repository truth in `AGENTS.md` and `.ai-tool-init/config.json`.
- Extend this skill with project-specific behavior instead of pushing repository details into the team layer.
{{projectGuardrails}}
