---
name: {{skillId}}
description: {{skillDescription}}
---

# {{skillId}}

This is a repo-local project skill generated by `ai-tool-init`.

Use this skill when repository-specific guidance must override the team layer.

## Guardrails

- Treat this project skill as higher priority than `.agents/skills/{{skillId}}` when both exist.
- Keep repository truth in `AGENTS.md` and `.ai-tool-init/config.json`.
- Extend this skill with project-specific behavior instead of pushing repository details into the team layer.
